-- Table: realtime_subway_positions

create table if not exists realtime_subway_positions (
    id bigint generated by default as identity primary key,
    line_id varchar(10),
    line_name varchar(50),
    station_id varchar(10),
    station_name varchar(50),
    train_number varchar(20),
    last_rec_date varchar(10), -- YYYYMMDD
    last_rec_time varchar(20), -- HHmmss or full timestamp string from API
    direction_type int, -- 0:Up/Inner, 1:Down/Outer
    dest_station_id varchar(10),
    dest_station_name varchar(50),
    train_status varchar(10), -- 0,1,2,3 code
    is_express varchar(5), -- '1', '0', '7'. Storing as string to be safe or int if consistent.
    is_last_train boolean,
    created_at timestamp with time zone default now()
);

-- Index recommendations
create index if not exists idx_line_name on realtime_subway_positions(line_name);
create index if not exists idx_train_number on realtime_subway_positions(train_number);
create index if not exists idx_created_at on realtime_subway_positions(created_at);
